### ISSUE TITLE
Enable text2Img module

### ISSUE THREAD

**Issue by Peterbins** [radykal/fpd-js#10]
I see a merge request "shopify-update" in which the module textToImage has been added (AI). I do not see it reflected in the documentation: https://jsdoc.fancyproductdesigner.com/Options and what the conditions are for enabling it. I am very curious.

**Comment by radykal** [comment]
Right now the ai features are not supported yet. We will come around with a solution for fpd-js soon.

**Comment by ArnoldSelly** [comment]
Have you added AI extension support for fpd-js yet?
