### ISSUE TITLE
addElement once the code isloaded

### ISSUE THREAD

**Issue by Peterbins** [radykal/fpd-js#12]
In the old version, you could still add yourDesigner.addElement("image", "images/designs/heart_circle.png", "Test"); once the code had loaded. I can't seem to find it in the current version, is that correct?

**Comment by radykal** [comment]
We added some function to the fabricjs canvas class. It is not documented yet, but will do later.

Example.
`fpd.currentViewInstance.fabricCanvas.addElement()`
