### ISSUE TITLE
License Inquiry

### ISSUE THREAD

**Issue by jared-leddy** [radykal/fpd-js#18]
I'd like to integrate this into a TS React app. Since it's not already TS, I'll want to rebuild the project.

In doing so, its likely that I will not keep everything exactly the same. 

Do I need my own agreement/license to do this? If so, who do I contact about it?

**Comment by radykal** [comment]
No, you can just change the source code to your needs.

**Comment by jared-leddy** [comment]
> No, you can just change the source code to your needs.

Awesome! Thank you.
