### ISSUE TITLE
Unable to fix an image element

### ISSUE THREAD

**Issue by Digiperf** [radykal/fpd-js#24]
Hello
I'm trying to make the image elements of my product fixed, without the user being able to move them.
I've tried these settings:
```
"draggable":false,
"rotatable":false,
"resizable":false,
"removable":false,
"flipX":false,
"flipY":false,
"zChangeable":false,
"uniScalingUnlockable":false,
"locked":true,
"fixed":true,
```
But it didn't work :

![image](https://github.com/radykal/fpd-js/assets/74869839/0e14f051-7fad-4395-9fc4-67cde9124391)

Thanks for your help

**Comment by Digiperf** [comment]
Hello @radykal can you help me please ?

**Comment by Digiperf** [comment]
@radykal raphael can you help me please ?

**Comment by Digiperf** [comment]
@radykal it's very urgent for us please ?
Thanks

**Comment by Digiperf** [comment]
@radykal I just saw your answer
Here's a staging URL : -https://staging.greetandgreen.com/customize/new/28

**Comment by radykal** [comment]
It seems you enabled the editorMode https://jsdoc.fancyproductdesigner.com/Options#Options.defaults.editorMode, which makes all elements editable. That mode is useful if you want to edit all elements despite the customizable props.

**Comment by Digiperf** [comment]
Thanks a lot @radykal  !!!
