### ISSUE TITLE
I can't the latest price in priceChange event

### ISSUE THREAD

**Issue by kratospan** [radykal/fpd-js#4]
I want to get the latest price and the code I write is:
`
fbq.addEventListenr('priceChange',(val) => {
    console.log('price',val)
})
`

and that concole shows 

![image](https://github.com/radykal/fpd-js/assets/46380968/70229a42-6391-4b9b-83d6-fe8014ea7ad0)

But I can't find elementPrice

![image](https://github.com/radykal/fpd-js/assets/46380968/8184dd72-0317-486e-b77d-42715a669c08)

**Comment by radykal** [comment]
You can get the current price of using currentPrice property of [FancyProductDesigner](https://jsdoc.fancyproductdesigner.com/FancyProductDesigner#FancyProductDesigner..currentPrice) class.

`fbq.currentPrice`

**Comment by kratospan** [comment]
OK thanks！I have already try it and it works.

**Comment by kratospan** [comment]
OK thanks！I have already try it and it works.
